default:
  image: node:24-slim

workflow:
  name: Dockerize app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

stages:
  - quality
  - test
  - build

linting_job:
  stage: quality
  before_script:
    - npm ci
  script:
    - npm run lint

unit_testing_job:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test:unit

integration_testing_job:
  stage: test
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_NAME: medias_test
    DATABASE_USER: postgres
    DATABASE_PASSWORD: test_password
    TEST_DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME"

    POSTGRES_DB: medias_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test_password
    PGPASSWORD: test_password
  before_script:
  - npm ci
  - apt-get update
  - apt-get install -y postgresql-client
  - until pg_isready -h "$DATABASE_HOST" -U "$DATABASE_USER" -d "$DATABASE_NAME"; do sleep 2; done
  - psql -h "$DATABASE_HOST" -U "$DATABASE_USER" -p "$DATABASE_PORT" -d "$DATABASE_NAME" -f sql/schema.sql
  script:
  - npm run test:integration

coverage_testing_job:
  stage: test
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_NAME: medias_test
    DATABASE_USER: postgres
    DATABASE_PASSWORD: test_password
    TEST_DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME"

    POSTGRES_DB: medias_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test_password
    PGPASSWORD: test_password
  before_script:
  - npm ci
  - apt-get update
  - apt-get install -y postgresql-client
  - until pg_isready -h "$DATABASE_HOST" -U "$DATABASE_USER" -d "$DATABASE_NAME"; do sleep 2; done
  - psql -h "$DATABASE_HOST" -U "$DATABASE_USER" -p "$DATABASE_PORT" -d "$DATABASE_NAME" -f sql/schema.sql
  script:
  - npm run test:coverage

building_job:
  stage: build
  image: docker:24.0.5-cli
  services:
  - name: docker:24.0.5-dind
    alias: docker
  script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  - docker run --privileged --rm tonistiigi/binfmt --install all
  - docker buildx create --use
  - docker buildx inspect --bootstrap
  
  - docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --target api-runtime \
    -t "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA" \
    --push \
    .

  - docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --target frontend-runtime \
    -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA" \
    --push \
    .
